[[libpng]]
arch = "aarch64"
git-tree-sha1 = "d4b632f86d7a9e08bf1528fac2c9484516f8bf2d"
os = "macos"

    [[libpng.download]]
    sha256 = "1e73e28801079891f3cd2d31c3dd11b72b0ea25119f6b1180c01c27da41d632d"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.aarch64-apple-darwin.tar.gz"
[[libpng]]
arch = "aarch64"
git-tree-sha1 = "48e41a5f3068deba2fd6071ce46e5c0ee63fef08"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "76e2738426be1b43af82999496d7dee0c89a623de1ae00a267d00209f46373b6"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.aarch64-linux-gnu.tar.gz"
[[libpng]]
arch = "aarch64"
git-tree-sha1 = "84ca2647091ef30bf58ebd9b6d0cd10c33a5bf75"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "8c677ef59e509a4c2ce016712b357793ca7262dffc7a407451307b2e7ef61c83"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.aarch64-linux-musl.tar.gz"
[[libpng]]
arch = "aarch64"
git-tree-sha1 = "a5611df11041396dda85973250c6a72df55572ab"
os = "freebsd"

    [[libpng.download]]
    sha256 = "57a89955c37b234fe61f005ce9d0f3db6c5151486ec9b38f8752fe3c70ff17e9"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.aarch64-unknown-freebsd.tar.gz"
[[libpng]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "38f9c29a040d975f3cd8cace37bd25e788531528"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "755d4828192e9b11cdda46e61b3bbcf8bb40363f25035819d1a179200ae17a83"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.armv6l-linux-gnueabihf.tar.gz"
[[libpng]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bd261989cae33c5c1f99f0de83cc2018fbf75bd4"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "cfd581da0e689c9e457ae2573b86209db9d28e456017290cd35a166024906192"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.armv6l-linux-musleabihf.tar.gz"
[[libpng]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d30f12634863f1e132631a73cee511fd37b50dae"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "f41df0c6dd1585b208e014e310a9cd99f57722cebde489f8211f9147b6c9eb10"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.armv7l-linux-gnueabihf.tar.gz"
[[libpng]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fd1bbf0bef2c8afdc11146273ae8513532e2f79a"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "dd3ea157425fdfaee4ffbb5f0ce56f0aecc6eec4cee96220b0a001fb2f151781"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.armv7l-linux-musleabihf.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "5e74c4eeaf15d5787b3c3244a92294f655fae17f"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "49716d5a6d8ccee5728e6ff39417ae2959eb9a5866b4347af62f2b44355ad19d"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.i686-linux-gnu.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "63652aa934fb519400aec116a746ed35bcf4c72e"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "3d33cf24049a37f5c34cc9eee7fc0b042357a6d5814dd58e7ea1b4a2a49feaa0"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.i686-linux-musl.tar.gz"
[[libpng]]
arch = "i686"
git-tree-sha1 = "597446606d7004850516d9bbeef8ab64ace71a4f"
os = "windows"

    [[libpng.download]]
    sha256 = "78792cab65f41837b437c5f6c24b024f692acc2873a03cb6df60f5bf953b8ca7"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.i686-w64-mingw32.tar.gz"
[[libpng]]
arch = "powerpc64le"
git-tree-sha1 = "6c86595873265d2c1213938fac3e64df3dab1625"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "fee66cf2932a58e45626ed4b783f31b8bbf325ce53ff3fecef6d6066fcb3d0e9"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.powerpc64le-linux-gnu.tar.gz"
[[libpng]]
arch = "riscv64"
git-tree-sha1 = "a4d4eceb875e7c8bbfc2da0c43f2fd92e2585d1b"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "60b2f373eeaaaca10a20ff3f73d9e56b745fd644256c657ca9c1bcf23af16ebe"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.riscv64-linux-gnu.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "f6b20ecfa48bdd65feca477ed4f2b135a5c85817"
os = "macos"

    [[libpng.download]]
    sha256 = "fa6651e545979be90e3138150bc6a72a3a1b903129b06150fe18b26292cdc95e"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.x86_64-apple-darwin.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "fc8f73f3a2dfd4e61a884c49972e00954fcdb4f0"
libc = "glibc"
os = "linux"

    [[libpng.download]]
    sha256 = "f12c92373d9d3d229a6d89a2de2e6e84138a332f828abf916aa193982181b49e"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.x86_64-linux-gnu.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "1a8128d00d77ce6f2289f68448f9b33a4c601026"
libc = "musl"
os = "linux"

    [[libpng.download]]
    sha256 = "34e311bbb6e8b5f0e4c63bb464c1dd09fac38aa001cd26d23d9482945111bf15"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.x86_64-linux-musl.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "6b686967c0fb1980b34b70b91dc92dcfbbfa4609"
os = "freebsd"

    [[libpng.download]]
    sha256 = "36ad63d22b482233c8eb00a105c68cfc83a32c3593cb72702a3de31f5ea56f22"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.x86_64-unknown-freebsd.tar.gz"
[[libpng]]
arch = "x86_64"
git-tree-sha1 = "9daf0456d54952aa3ac9f2d242eeec7acabf7c1e"
os = "windows"

    [[libpng.download]]
    sha256 = "b389d3ac7040d97526409edb6d0c3b8055773ed29216268334b42be470ea4ac4"
    url = "https://github.com/JuliaBinaryWrappers/libpng_jll.jl/releases/download/libpng-v1.6.53+0/libpng.v1.6.53.x86_64-w64-mingw32.tar.gz"
